
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Feb 25 2024 02:26:40 CST (Feb 25 2024 08:26:40 UTC)

// Verification Directory fv/InstMem 

module InstMem(Addr, Size, DataOut, CLK);
  input [31:0] Addr;
  input [1:0] Size;
  input CLK;
  output [31:0] DataOut;
  wire [31:0] Addr;
  wire [1:0] Size;
  wire CLK;
  wire [31:0] DataOut;
  assign DataOut[0] = 1'b0;
  assign DataOut[1] = 1'b0;
  assign DataOut[2] = 1'b0;
  assign DataOut[3] = 1'b0;
  assign DataOut[4] = 1'b0;
  assign DataOut[5] = 1'b0;
  assign DataOut[6] = 1'b0;
  assign DataOut[7] = 1'b0;
  assign DataOut[8] = 1'b0;
  assign DataOut[9] = 1'b0;
  assign DataOut[10] = 1'b0;
  assign DataOut[11] = 1'b0;
  assign DataOut[12] = 1'b0;
  assign DataOut[13] = 1'b0;
  assign DataOut[14] = 1'b0;
  assign DataOut[15] = 1'b0;
  assign DataOut[16] = 1'b0;
  assign DataOut[17] = 1'b0;
  assign DataOut[18] = 1'b0;
  assign DataOut[19] = 1'b0;
  assign DataOut[20] = 1'b0;
  assign DataOut[21] = 1'b0;
  assign DataOut[22] = 1'b0;
  assign DataOut[23] = 1'b0;
  assign DataOut[24] = 1'b0;
  assign DataOut[25] = 1'b0;
  assign DataOut[26] = 1'b0;
  assign DataOut[27] = 1'b0;
  assign DataOut[28] = 1'b0;
  assign DataOut[29] = 1'b0;
  assign DataOut[30] = 1'b0;
  assign DataOut[31] = 1'b0;
endmodule

