
//input ports
add mapped point opA[31] opA[31]
add mapped point opA[30] opA[30]
add mapped point opA[29] opA[29]
add mapped point opA[28] opA[28]
add mapped point opA[27] opA[27]
add mapped point opA[26] opA[26]
add mapped point opA[25] opA[25]
add mapped point opA[24] opA[24]
add mapped point opA[23] opA[23]
add mapped point opA[22] opA[22]
add mapped point opA[21] opA[21]
add mapped point opA[20] opA[20]
add mapped point opA[19] opA[19]
add mapped point opA[18] opA[18]
add mapped point opA[17] opA[17]
add mapped point opA[16] opA[16]
add mapped point opA[15] opA[15]
add mapped point opA[14] opA[14]
add mapped point opA[13] opA[13]
add mapped point opA[12] opA[12]
add mapped point opA[11] opA[11]
add mapped point opA[10] opA[10]
add mapped point opA[9] opA[9]
add mapped point opA[8] opA[8]
add mapped point opA[7] opA[7]
add mapped point opA[6] opA[6]
add mapped point opA[5] opA[5]
add mapped point opA[4] opA[4]
add mapped point opA[3] opA[3]
add mapped point opA[2] opA[2]
add mapped point opA[1] opA[1]
add mapped point opA[0] opA[0]
add mapped point opB[31] opB[31]
add mapped point opB[30] opB[30]
add mapped point opB[29] opB[29]
add mapped point opB[28] opB[28]
add mapped point opB[27] opB[27]
add mapped point opB[26] opB[26]
add mapped point opB[25] opB[25]
add mapped point opB[24] opB[24]
add mapped point opB[23] opB[23]
add mapped point opB[22] opB[22]
add mapped point opB[21] opB[21]
add mapped point opB[20] opB[20]
add mapped point opB[19] opB[19]
add mapped point opB[18] opB[18]
add mapped point opB[17] opB[17]
add mapped point opB[16] opB[16]
add mapped point opB[15] opB[15]
add mapped point opB[14] opB[14]
add mapped point opB[13] opB[13]
add mapped point opB[12] opB[12]
add mapped point opB[11] opB[11]
add mapped point opB[10] opB[10]
add mapped point opB[9] opB[9]
add mapped point opB[8] opB[8]
add mapped point opB[7] opB[7]
add mapped point opB[6] opB[6]
add mapped point opB[5] opB[5]
add mapped point opB[4] opB[4]
add mapped point opB[3] opB[3]
add mapped point opB[2] opB[2]
add mapped point opB[1] opB[1]
add mapped point opB[0] opB[0]
add mapped point func[2] func[2]
add mapped point func[1] func[1]
add mapped point func[0] func[0]
add mapped point auxFunc[6] auxFunc[6]
add mapped point auxFunc[5] auxFunc[5]
add mapped point auxFunc[4] auxFunc[4]
add mapped point auxFunc[3] auxFunc[3]
add mapped point auxFunc[2] auxFunc[2]
add mapped point auxFunc[1] auxFunc[1]
add mapped point auxFunc[0] auxFunc[0]

//output ports
add mapped point out[31] out[31]
add mapped point out[30] out[30]
add mapped point out[29] out[29]
add mapped point out[28] out[28]
add mapped point out[27] out[27]
add mapped point out[26] out[26]
add mapped point out[25] out[25]
add mapped point out[24] out[24]
add mapped point out[23] out[23]
add mapped point out[22] out[22]
add mapped point out[21] out[21]
add mapped point out[20] out[20]
add mapped point out[19] out[19]
add mapped point out[18] out[18]
add mapped point out[17] out[17]
add mapped point out[16] out[16]
add mapped point out[15] out[15]
add mapped point out[14] out[14]
add mapped point out[13] out[13]
add mapped point out[12] out[12]
add mapped point out[11] out[11]
add mapped point out[10] out[10]
add mapped point out[9] out[9]
add mapped point out[8] out[8]
add mapped point out[7] out[7]
add mapped point out[6] out[6]
add mapped point out[5] out[5]
add mapped point out[4] out[4]
add mapped point out[3] out[3]
add mapped point out[2] out[2]
add mapped point out[1] out[1]
add mapped point out[0] out[0]

//inout ports




//Sequential Pins
add mapped point booth1/accumulator_reg[0]/q booth1/accumulator_reg[0]_reg/Q 
add mapped point booth1/accumulator_reg[1]/q booth1/accumulator_reg[1]_reg/Q 
add mapped point booth1/accumulator_reg[2]/q booth1/accumulator_reg[2]_reg/Q 
add mapped point booth1/accumulator_reg[3]/q booth1/accumulator_reg[3]_reg/Q 
add mapped point booth1/accumulator_reg[4]/q booth1/accumulator_reg[4]_reg/Q 
add mapped point booth1/accumulator_reg[5]/q booth1/accumulator_reg[5]_reg/Q 
add mapped point booth1/accumulator_reg[6]/q booth1/accumulator_reg[6]_reg/Q 
add mapped point booth1/accumulator_reg[7]/q booth1/accumulator_reg[7]_reg/Q 
add mapped point booth1/accumulator_reg[8]/q booth1/accumulator_reg[8]_reg/Q 
add mapped point booth1/accumulator_reg[9]/q booth1/accumulator_reg[9]_reg/Q 
add mapped point booth1/accumulator_reg[10]/q booth1/accumulator_reg[10]_reg/Q 
add mapped point booth1/accumulator_reg[11]/q booth1/accumulator_reg[11]_reg/Q 
add mapped point booth1/accumulator_reg[12]/q booth1/accumulator_reg[12]_reg/Q 
add mapped point booth1/accumulator_reg[13]/q booth1/accumulator_reg[13]_reg/Q 
add mapped point booth1/accumulator_reg[14]/q booth1/accumulator_reg[14]_reg/Q 
add mapped point booth1/accumulator_reg[15]/q booth1/accumulator_reg[15]_reg/Q 
add mapped point booth1/accumulator_reg[16]/q booth1/accumulator_reg[16]_reg/Q 
add mapped point booth1/accumulator_reg[17]/q booth1/accumulator_reg[17]_reg/Q 
add mapped point booth1/accumulator_reg[18]/q booth1/accumulator_reg[18]_reg/Q 
add mapped point booth1/accumulator_reg[19]/q booth1/accumulator_reg[19]_reg/Q 
add mapped point booth1/accumulator_reg[20]/q booth1/accumulator_reg[20]_reg/Q 
add mapped point booth1/accumulator_reg[21]/q booth1/accumulator_reg[21]_reg/Q 
add mapped point booth1/accumulator_reg[22]/q booth1/accumulator_reg[22]_reg/Q 
add mapped point booth1/accumulator_reg[23]/q booth1/accumulator_reg[23]_reg/Q 
add mapped point booth1/accumulator_reg[24]/q booth1/accumulator_reg[24]_reg/Q 
add mapped point booth1/accumulator_reg[25]/q booth1/accumulator_reg[25]_reg/Q 
add mapped point booth1/accumulator_reg[26]/q booth1/accumulator_reg[26]_reg/Q 
add mapped point booth1/accumulator_reg[27]/q booth1/accumulator_reg[27]_reg/Q 
add mapped point booth1/accumulator_reg[28]/q booth1/accumulator_reg[28]_reg/Q 
add mapped point booth1/accumulator_reg[29]/q booth1/accumulator_reg[29]_reg/Q 
add mapped point booth1/accumulator_reg[30]/q booth1/accumulator_reg[30]_reg/Q 
add mapped point booth1/accumulator_reg[31]/q booth1/accumulator_reg[31]_reg/Q 
add mapped point booth1/accumulator_reg[32]/q booth1/accumulator_reg[32]_reg/Q 
add mapped point booth1/accumulator_reg[33]/q booth1/accumulator_reg[33]_reg/Q 
add mapped point booth1/accumulator_reg[34]/q booth1/accumulator_reg[34]_reg/Q 
add mapped point booth1/accumulator_reg[35]/q booth1/accumulator_reg[35]_reg/Q 
add mapped point booth1/accumulator_reg[36]/q booth1/accumulator_reg[36]_reg/Q 
add mapped point booth1/accumulator_reg[37]/q booth1/accumulator_reg[37]_reg/Q 
add mapped point booth1/accumulator_reg[38]/q booth1/accumulator_reg[38]_reg/Q 
add mapped point booth1/accumulator_reg[39]/q booth1/accumulator_reg[39]_reg/Q 
add mapped point booth1/accumulator_reg[40]/q booth1/accumulator_reg[40]_reg/Q 
add mapped point booth1/accumulator_reg[41]/q booth1/accumulator_reg[41]_reg/Q 
add mapped point booth1/accumulator_reg[42]/q booth1/accumulator_reg[42]_reg/Q 
add mapped point booth1/accumulator_reg[43]/q booth1/accumulator_reg[43]_reg/Q 
add mapped point booth1/accumulator_reg[44]/q booth1/accumulator_reg[44]_reg/Q 
add mapped point booth1/accumulator_reg[45]/q booth1/accumulator_reg[45]_reg/Q 
add mapped point booth1/accumulator_reg[46]/q booth1/accumulator_reg[46]_reg/Q 
add mapped point booth1/accumulator_reg[47]/q booth1/accumulator_reg[47]_reg/Q 
add mapped point booth1/accumulator_reg[48]/q booth1/accumulator_reg[48]_reg/Q 
add mapped point booth1/accumulator_reg[49]/q booth1/accumulator_reg[49]_reg/Q 
add mapped point booth1/accumulator_reg[50]/q booth1/accumulator_reg[50]_reg/Q 
add mapped point booth1/accumulator_reg[51]/q booth1/accumulator_reg[51]_reg/Q 
add mapped point booth1/accumulator_reg[52]/q booth1/accumulator_reg[52]_reg/Q 
add mapped point booth1/accumulator_reg[53]/q booth1/accumulator_reg[53]_reg/Q 
add mapped point booth1/accumulator_reg[54]/q booth1/accumulator_reg[54]_reg/Q 
add mapped point booth1/accumulator_reg[55]/q booth1/accumulator_reg[55]_reg/Q 
add mapped point booth1/accumulator_reg[56]/q booth1/accumulator_reg[56]_reg/Q 
add mapped point booth1/accumulator_reg[57]/q booth1/accumulator_reg[57]_reg/Q 
add mapped point booth1/accumulator_reg[58]/q booth1/accumulator_reg[58]_reg/Q 
add mapped point booth1/accumulator_reg[59]/q booth1/accumulator_reg[59]_reg/Q 
add mapped point booth1/accumulator_reg[60]/q booth1/accumulator_reg[60]_reg/Q 
add mapped point booth1/accumulator_reg[61]/q booth1/accumulator_reg[61]_reg/Q 
add mapped point booth1/accumulator_reg[62]/q booth1/accumulator_reg[62]_reg/Q 
add mapped point myOutput[0]/q myOutput_reg[0]/Q 
add mapped point myOutput[1]/q myOutput_reg[1]/Q 
add mapped point myOutput[2]/q myOutput_reg[2]/Q 
add mapped point myOutput[3]/q myOutput_reg[3]/Q 
add mapped point myOutput[4]/q myOutput_reg[4]/Q 
add mapped point myOutput[5]/q myOutput_reg[5]/Q 
add mapped point myOutput[6]/q myOutput_reg[6]/Q 
add mapped point myOutput[7]/q myOutput_reg[7]/Q 
add mapped point myOutput[8]/q myOutput_reg[8]/Q 
add mapped point myOutput[9]/q myOutput_reg[9]/Q 
add mapped point myOutput[10]/q myOutput_reg[10]/Q 
add mapped point myOutput[11]/q myOutput_reg[11]/Q 
add mapped point myOutput[12]/q myOutput_reg[12]/Q 
add mapped point myOutput[13]/q myOutput_reg[13]/Q 
add mapped point myOutput[14]/q myOutput_reg[14]/Q 
add mapped point myOutput[15]/q myOutput_reg[15]/Q 
add mapped point myOutput[16]/q myOutput_reg[16]/Q 
add mapped point myOutput[17]/q myOutput_reg[17]/Q 
add mapped point myOutput[18]/q myOutput_reg[18]/Q 
add mapped point myOutput[19]/q myOutput_reg[19]/Q 
add mapped point myOutput[20]/q myOutput_reg[20]/Q 
add mapped point myOutput[21]/q myOutput_reg[21]/Q 
add mapped point myOutput[22]/q myOutput_reg[22]/Q 
add mapped point myOutput[23]/q myOutput_reg[23]/Q 
add mapped point myOutput[24]/q myOutput_reg[24]/Q 
add mapped point myOutput[25]/q myOutput_reg[25]/Q 
add mapped point myOutput[26]/q myOutput_reg[26]/Q 
add mapped point myOutput[27]/q myOutput_reg[27]/Q 
add mapped point myOutput[28]/q myOutput_reg[28]/Q 
add mapped point myOutput[29]/q myOutput_reg[29]/Q 
add mapped point myOutput[30]/q myOutput_reg[30]/Q 
add mapped point myOutput[31]/q myOutput_reg[31]/Q 



//Black Boxes
